//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addr
    {
        public Addr()
        {
            this.Users = new HashSet<User>();
        }
    
        public int addrId { get; set; }
        public Nullable<int> conntryId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
