//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Addrs = new HashSet<Addr>();
        }
    
        public int countryId { get; set; }
        public string countryName { get; set; }
        public Nullable<int> countyId { get; set; }
    
        public virtual ICollection<Addr> Addrs { get; set; }
        public virtual County County { get; set; }
    }
}
