//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite
    {
        public Favorite()
        {
            this.Favorite_User = new HashSet<Favorite_User>();
        }
    
        public int favoriteId { get; set; }
        public string favoriteName { get; set; }
    
        public virtual ICollection<Favorite_User> Favorite_User { get; set; }
    }
}
