//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite_User
    {
        public Favorite_User()
        {
            this.Users = new HashSet<User>();
        }
    
        public int favorite_UserId { get; set; }
        public Nullable<int> favoriteId { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual Favorite Favorite { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
